print("CB-1.5.1B — Session Security")
print("session_token=server-generated cryptographic ownership proof")
print("token_storage=SHA-256 hash only")
print("history=token protected")
print("reset=token protected")
print("continuation=token protected")
print("rotation=old token invalidated")
print("migration=legacy unprotected rows remain readable until first API claim")
print("widget=token persisted separately from session_id")
